{{- if .Values.ingress.meta.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "longbow.fullname" . }}-meta
  labels:
    {{- include "longbow.labels" . | nindent 4 }}
  {{- with .Values.ingress.meta.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.meta.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.meta.tls }}
  tls:
    {{- range .Values.ingress.meta.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.meta.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "longbow.fullname" $ }}-meta
                port:
                  number: {{ $.Values.service.meta.port }}
          {{- end }}
    {{- end }}
{{- end }}
