
{{- if .Values.persistence.wal.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "longbow.fullname" . }}-wal
  labels:
    {{- include "longbow.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.wal.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.wal.size | quote }}
  {{- if .Values.persistence.wal.storageClass }}
  storageClassName: {{ .Values.persistence.wal.storageClass | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.persistence.snapshots.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "longbow.fullname" . }}-snapshots
  labels:
    {{- include "longbow.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.snapshots.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.snapshots.size | quote }}
  {{- if .Values.persistence.snapshots.storageClass }}
  storageClassName: {{ .Values.persistence.snapshots.storageClass | quote }}
  {{- end }}
{{- end }}
