{{- if eq .Values.gossip.discovery.provider "k8s" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "longbow.fullname" . }}-discovery
  labels:
    {{- include "longbow.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
{{- end }}
