{{- if eq .Values.gossip.discovery.provider "k8s" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "longbow.fullname" . }}-discovery
  labels:
    {{- include "longbow.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "longbow.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "longbow.fullname" . }}-discovery
  apiGroup: rbac.authorization.k8s.io
{{- end }}
