apiVersion: v1
kind: Service
metadata:
  name: {{ include "longbow.fullname" . }}
  labels:
    {{- include "longbow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc-data
      protocol: TCP
      name: grpc-data
    - port: {{ .Values.service.metaPort }}
      targetPort: grpc-meta
      protocol: TCP
      name: grpc-meta
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "longbow.selectorLabels" . | nindent 4 }}
