{{- if .Values.service.data.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "longbow.fullname" . }}-data
  labels:
    {{- include "longbow.labels" . | nindent 4 }}
  {{- with .Values.service.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.data.type }}
  ports:
    - port: {{ .Values.service.data.port }}
      targetPort: grpc-data
      protocol: TCP
      name: grpc-data
  selector:
    {{- include "longbow.selectorLabels" . | nindent 4 }}
{{- end }}
