{{- if .Values.service.meta.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "longbow.fullname" . }}-meta
  labels:
    {{- include "longbow.labels" . | nindent 4 }}
  {{- with .Values.service.meta.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.meta.type }}
  ports:
    - port: {{ .Values.service.meta.port }}
      targetPort: grpc-meta
      protocol: TCP
      name: grpc-meta
  selector:
    {{- include "longbow.selectorLabels" . | nindent 4 }}
{{- end }}
